version: 0.2
    
phases:
  install:
    runtime-versions:
      docker: 18
    commands:                                                                 
      - make install
  buil:
    commands:
      - make lint
      - make test
  post_build:
    commands:
      - echo testing completed `date`